name: my first workflow
on: workflow_dispatch
jobs:
  job1:
    runs-on: ubuntu-22.04
    steps:
    - name: update apt repository
      run: sudo apt update
    - name: install php package
      run: sudo apt install php -y
    - name: Check version
      run: php --version
  job2: 
    runs-on: ubuntu-22.04
    steps:
    - name: install php package
      run: |
        sudo apt update
        sudo apt install php -y
        php --version
  job3:
    runs-on: ubuntu-latest
    steps:
    - name: install python
      uses: actions/setup-python@v7
      with:
        python-version: '3.13'
        
    
  
  
